In [1]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv


# import libraries

In [2]:
import numpy as np
import pandas as pd

In [3]:
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')

In [4]:
tips.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


# create np-array

# 1. create 1D, 2D, 3D and 4D array using np.array()

In [5]:
#1D
a = np.array([1,2,3,4,5])
print(a)
print(a.ndim)
print(a.shape)

[1 2 3 4 5]
1
(5,)


In [6]:
#2D
b = np.array([ [1,2,3],[4,5,6] ])
print(b)
print(b.ndim)
print(b.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [7]:
#3D
c = np.array([ [[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]] ])
print(c)
print(c.ndim)
print(c.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)


In [8]:
#4D
d = np.array([ [[[1,2,3],[4,5,6]],[[0,-5,9],[0,9,4]]], [[[7,8,9],[10,11,12]],[[0,-5,9],[0,9,4]]], [[[13,14,15],[16,17,18]],[[0,-5,9],[0,9,4]]] ])
print(d)
print(d.ndim)
print(d.shape)


[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 0 -5  9]
   [ 0  9  4]]]


 [[[ 7  8  9]
   [10 11 12]]

  [[ 0 -5  9]
   [ 0  9  4]]]


 [[[13 14 15]
   [16 17 18]]

  [[ 0 -5  9]
   [ 0  9  4]]]]
4
(3, 2, 2, 3)


# create 1D, 2D, 3D and 4D array using arange() and reshape()

In [9]:
#1D
m = np.arange(1,11)
print(m)
print(m.ndim)
print(m.shape)


[ 1  2  3  4  5  6  7  8  9 10]
1
(10,)


In [10]:
#2D
n = np.arange(1,11).reshape(2,5)
print(n)
print(n.ndim)
print(n.shape)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
(2, 5)


In [11]:
#3D
p = np.arange(1,31).reshape(3,2,5)
print(p)
print(p.ndim)
print(p.shape)


[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]
3
(3, 2, 5)


# create array using ones and zeros

In [12]:
#Zeros
u = np.zeros(5, dtype = int)
print(u)

[0 0 0 0 0]


In [13]:
j = np.random.randint(1,1000, (4,3,3,4) )
print(j)

[[[[255 266 636 100]
   [ 74 919 351 620]
   [241 168 426 476]]

  [[357 525 598 943]
   [627 328 926 331]
   [646 619 485 210]]

  [[395 409 879 966]
   [ 47 693 799 289]
   [ 25 200 385 128]]]


 [[[172 668 671 201]
   [319 106 161 374]
   [746 265 818 254]]

  [[665 132 299 190]
   [312 726 592 634]
   [533 553 466 900]]

  [[487 418 382 266]
   [835 586 781 949]
   [511 381 777 180]]]


 [[[930 998 717 989]
   [ 11 189 604 358]
   [994 979 997 286]]

  [[679 559 501 578]
   [716 469 443 279]
   [163 126 204 126]]

  [[359 827 675 300]
   [767 792 150 852]
   [659 537 761 240]]]


 [[[935 288 709 464]
   [655 957 834 601]
   [184 957  23 821]]

  [[915 665 698 299]
   [108 192 368 611]
   [524 440  49 775]]

  [[325 804 431 719]
   [315  22 736 637]
   [646 866 331 796]]]]


# using linspace

# create 1D array of tip from tips dataframe

# create 2D array of tip and total_bill form tips dataframe

# practice atleast 2 example for each using ndim, shape, size and itemsize

# change data type and memory size of any np-array using astype()

# create 2 same dimensional array and do scalar and vector operations

# find minimun and maximum tip

# find average total_bill and average tip

# find median total_bill

# find standard deviasion and variance of tip

# find log values of tip

# apply round, floor and ceil operation on tip array

# use 1D, 2D and 3D np-array, and apply indexing and slicing atleast 5 example for each (take example as your wish)

# stacking and spliting

In [14]:
d = np.arange(27).reshape(3,9)
e = np.arange(28,55).reshape(3,9)

# use hstack() and vstack()

# use hsplit() and vsplit()

### 