In [201]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv


# import libraries

In [202]:
import numpy as np
import pandas as pd

In [203]:
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')

In [204]:
tips.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


# create np-array

# 1. create 1D, 2D, 3D and 4D array using np.array()

In [205]:
#1D
a = np.array([1,2,3,4,5])
print(a)
print(a.ndim)
print(a.shape)

[1 2 3 4 5]
1
(5,)


In [206]:
#2D
b = np.array([ [1,2,3],[4,5,6] ])
print(b)
print(b.ndim)
print(b.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [207]:
#3D
c = np.array([ [[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]],[[8,4,-2],[-1,7,0]] ])
print(c)
print(c.ndim)
print(c.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 8  4 -2]
  [-1  7  0]]]
3
(3, 2, 3)


In [208]:

#4D
d = np.array([ [[[1,2,3],[4,5,6]],[[0,-5,9],[0,9,4]]], [[[7,8,9],[10,11,12]],[[0,-5,9],[0,9,4]]], [[[13,14,15],[16,17,18]],[[0,-5,9],[0,9,4]]] ])
print(d)
print(d.ndim)
print(d.shape)
print(d.size)
print(d.itemsize)






[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 0 -5  9]
   [ 0  9  4]]]


 [[[ 7  8  9]
   [10 11 12]]

  [[ 0 -5  9]
   [ 0  9  4]]]


 [[[13 14 15]
   [16 17 18]]

  [[ 0 -5  9]
   [ 0  9  4]]]]
4
(3, 2, 2, 3)
36
8


# create 1D, 2D, 3D and 4D array using arange() and reshape()

In [209]:
#1D
m = np.arange(1,11)
print(m)
print(m.ndim)
print(m.shape)


[ 1  2  3  4  5  6  7  8  9 10]
1
(10,)


In [210]:
#2D
n = np.arange(1,11).reshape(2,5)
print(n)
print(n.ndim)
print(n.shape)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
(2, 5)


In [211]:
#3D
p = np.arange(1,31).reshape(3,2,5)
print(p)
print(p.ndim)
print(p.shape)


[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]
3
(3, 2, 5)


# create array using ones and zeros

In [212]:
#Zeros
u = np.zeros(5, dtype = int)
print(u)

[0 0 0 0 0]


In [213]:
j = np.random.randint(1,1000, (4,3,3,4) )
print(j)

[[[[231 331 575 442]
   [270 619  25 623]
   [755 479 906 555]]

  [[557 113  77 974]
   [644 784  34  86]
   [720 732 129 679]]

  [[564 306  47 729]
   [794 639 233 370]
   [161 512 400 376]]]


 [[[382 523  95 786]
   [555 970 831  99]
   [  3 322 712 311]]

  [[722 201 874 400]
   [872 606 414 102]
   [268 719 432 888]]

  [[404 733 361 809]
   [357 626 700 167]
   [415 611 762  35]]]


 [[[589 899 553 482]
   [171 750 780 485]
   [640 892 503 623]]

  [[883  79 966  32]
   [658 435 117 770]
   [ 83 282 400 904]]

  [[922 591 223 966]
   [914 150  57 689]
   [413  72 697 562]]]


 [[[ 27  13 922 277]
   [714  51 151 562]
   [679 515 847 115]]

  [[722 679 810 622]
   [388 931 572 194]
   [530 626 462 849]]

  [[269 382 241 187]
   [ 11 948 171 305]
   [926 132 569 621]]]]


# using linspace

In [214]:
r = np.linspace(1,101,10, dtype = int)
r

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 101])

# create 1D array of tip from tips dataframe

In [215]:
T = tips['tip'].to_numpy()
print(T)

[ 1.01  1.66  3.5   3.31  3.61  4.71  2.    3.12  1.96  3.23  1.71  5.
  1.57  3.    3.02  3.92  1.67  3.71  3.5   3.35  4.08  2.75  2.23  7.58
  3.18  2.34  2.    2.    4.3   3.    1.45  2.5   3.    2.45  3.27  3.6
  2.    3.07  2.31  5.    2.24  2.54  3.06  1.32  5.6   3.    5.    6.
  2.05  3.    2.5   2.6   5.2   1.56  4.34  3.51  3.    1.5   1.76  6.73
  3.21  2.    1.98  3.76  2.64  3.15  2.47  1.    2.01  2.09  1.97  3.
  3.14  5.    2.2   1.25  3.08  4.    3.    2.71  3.    3.4   1.83  5.
  2.03  5.17  2.    4.    5.85  3.    3.    3.5   1.    4.3   3.25  4.73
  4.    1.5   3.    1.5   2.5   3.    2.5   3.48  4.08  1.64  4.06  4.29
  3.76  4.    3.    1.    4.    2.55  4.    3.5   5.07  1.5   1.8   2.92
  2.31  1.68  2.5   2.    2.52  4.2   1.48  2.    2.    2.18  1.5   2.83
  1.5   2.    3.25  1.25  2.    2.    2.    2.75  3.5   6.7   5.    5.
  2.3   1.5   1.36  1.63  1.73  2.    2.5   2.    2.74  2.    2.    5.14
  5.    3.75  2.61  2.    3.5   2.5   2.    2.    3.    3.48  

# create 2D array of tip and total_bill form tips dataframe

In [216]:
Q = tips[['tip','total_bill']].to_numpy()
print(Q)
print(Q.ndim)


[[ 1.01 16.99]
 [ 1.66 10.34]
 [ 3.5  21.01]
 [ 3.31 23.68]
 [ 3.61 24.59]
 [ 4.71 25.29]
 [ 2.    8.77]
 [ 3.12 26.88]
 [ 1.96 15.04]
 [ 3.23 14.78]
 [ 1.71 10.27]
 [ 5.   35.26]
 [ 1.57 15.42]
 [ 3.   18.43]
 [ 3.02 14.83]
 [ 3.92 21.58]
 [ 1.67 10.33]
 [ 3.71 16.29]
 [ 3.5  16.97]
 [ 3.35 20.65]
 [ 4.08 17.92]
 [ 2.75 20.29]
 [ 2.23 15.77]
 [ 7.58 39.42]
 [ 3.18 19.82]
 [ 2.34 17.81]
 [ 2.   13.37]
 [ 2.   12.69]
 [ 4.3  21.7 ]
 [ 3.   19.65]
 [ 1.45  9.55]
 [ 2.5  18.35]
 [ 3.   15.06]
 [ 2.45 20.69]
 [ 3.27 17.78]
 [ 3.6  24.06]
 [ 2.   16.31]
 [ 3.07 16.93]
 [ 2.31 18.69]
 [ 5.   31.27]
 [ 2.24 16.04]
 [ 2.54 17.46]
 [ 3.06 13.94]
 [ 1.32  9.68]
 [ 5.6  30.4 ]
 [ 3.   18.29]
 [ 5.   22.23]
 [ 6.   32.4 ]
 [ 2.05 28.55]
 [ 3.   18.04]
 [ 2.5  12.54]
 [ 2.6  10.29]
 [ 5.2  34.81]
 [ 1.56  9.94]
 [ 4.34 25.56]
 [ 3.51 19.49]
 [ 3.   38.01]
 [ 1.5  26.41]
 [ 1.76 11.24]
 [ 6.73 48.27]
 [ 3.21 20.29]
 [ 2.   13.81]
 [ 1.98 11.02]
 [ 3.76 18.29]
 [ 2.64 17.59]
 [ 3.15 20.08]
 [ 2.47 16

# practice atleast 2 example for each using ndim, shape, size and itemsize

In [217]:
#already done it another section

# change data type and memory size of any np-array using astype()

In [218]:
#also use it another section

# create 2 same dimensional array and do scalar and vector operations

In [219]:
# o = np.array([[1,2,3], [5,6,9]])
# u = np.array([[10,29,20], [50,60,90]])
# print("Scaler OP")
# print(o+17)
# print(u-50)
# print(o*10)
# print(u/5)
# print((u/5).astype(int))
# print(np.round(u/5).astype(int))# ROUND ALWAYS FLOAT ANS DEY
# print("Vector OP")
# print(o+u)
# print(o-u)
# print(o*u)
# print(u/o)


o = np.random.randint(1,50,(3,3)) 
u = np.random.randint(60,100,(3,3)) 
print(v)
print(z)
print("Scaler OP")
print(o+17)
print(u-50)
print(o*10)
print(u/5)
print((u/5).astype(int))
print(np.round(u/5))
print(np.round(u/5).astype(int)) # ROUND ALWAYS FLOAT ANS DEY
print(np.ceil(u/5))
print(np.ceil(u/5).astype(int))# CEIL ALWAYS FLOAT ANS DEY
print("Vector OP")
print(o+u)
print(o-u)
print(o*u)
print(u/o)
print(np.round(u/o).astype(int))

[[32 18 48]
 [45  3 19]
 [12 33 12]]
[1 2 3 4 5 6]
Scaler OP
[[58 54 33]
 [28 46 60]
 [32 48 24]]
[[47 35 13]
 [28 12 20]
 [43 27 27]]
[[410 370 160]
 [110 290 430]
 [150 310  70]]
[[19.4 17.  12.6]
 [15.6 12.4 14. ]
 [18.6 15.4 15.4]]
[[19 17 12]
 [15 12 14]
 [18 15 15]]
[[19. 17. 13.]
 [16. 12. 14.]
 [19. 15. 15.]]
[[19 17 13]
 [16 12 14]
 [19 15 15]]
[[20. 17. 13.]
 [16. 13. 14.]
 [19. 16. 16.]]
[[20 17 13]
 [16 13 14]
 [19 16 16]]
Vector OP
[[138 122  79]
 [ 89  91 113]
 [108 108  84]]
[[-56 -48 -47]
 [-67 -33 -27]
 [-78 -46 -70]]
[[3977 3145 1008]
 [ 858 1798 3010]
 [1395 2387  539]]
[[ 2.36585366  2.2972973   3.9375    ]
 [ 7.09090909  2.13793103  1.62790698]
 [ 6.2         2.48387097 11.        ]]
[[ 2  2  4]
 [ 7  2  2]
 [ 6  2 11]]


# find minimun and maximum tip

In [220]:
#MIN = np.min(T)
s = np.min(tips['tip'].to_numpy())
print(s)
#print(tips['tip'].sort_values().head(5)) #gpt theke shiksi

1.0


# find average total_bill and average tip

In [221]:
avgbill = round(np.mean(tips['total_bill'].to_numpy()),2)
avgtip = round(np.mean(tips['tip'].to_numpy()),3)

print(avgbill)
print(avgtip)

19.79
2.998


# find median total_bill

In [222]:
avgbill = round(np.median(tips['total_bill'].to_numpy()),2)
print(avgbill)

17.8


# find standard deviasion and variance of tip

In [223]:
print( np.var(T))
print( np.std(T))

1.9066085124966412
1.3807999538298954


# find log values of tip

In [224]:
print(np.log(T))

[0.00995033 0.5068176  1.25276297 1.19694819 1.28370777 1.54968791
 0.69314718 1.137833   0.67294447 1.17248214 0.53649337 1.60943791
 0.45107562 1.09861229 1.10525683 1.36609165 0.51282363 1.31103188
 1.25276297 1.20896035 1.40609699 1.01160091 0.80200159 2.0255132
 1.1568812  0.85015093 0.69314718 0.69314718 1.45861502 1.09861229
 0.37156356 0.91629073 1.09861229 0.89608802 1.18478998 1.28093385
 0.69314718 1.12167756 0.83724752 1.60943791 0.80647587 0.93216408
 1.11841492 0.27763174 1.7227666  1.09861229 1.60943791 1.79175947
 0.71783979 1.09861229 0.91629073 0.95551145 1.64865863 0.44468582
 1.46787435 1.25561604 1.09861229 0.40546511 0.56531381 1.90657514
 1.16627094 0.69314718 0.68309684 1.32441896 0.97077892 1.14740245
 0.90421815 0.         0.69813472 0.73716407 0.67803354 1.09861229
 1.1442228  1.60943791 0.78845736 0.22314355 1.1249296  1.38629436
 1.09861229 0.99694863 1.09861229 1.22377543 0.60431597 1.60943791
 0.70803579 1.64287269 0.69314718 1.38629436 1.76644166 1.09861

# apply round, floor and ceil operation on tip array

In [225]:
print(np.round(T).astype(int))
print(np.ceil(T).astype(int))
print(np.floor(T).astype(int))

[ 1  2  4  3  4  5  2  3  2  3  2  5  2  3  3  4  2  4  4  3  4  3  2  8
  3  2  2  2  4  3  1  2  3  2  3  4  2  3  2  5  2  3  3  1  6  3  5  6
  2  3  2  3  5  2  4  4  3  2  2  7  3  2  2  4  3  3  2  1  2  2  2  3
  3  5  2  1  3  4  3  3  3  3  2  5  2  5  2  4  6  3  3  4  1  4  3  5
  4  2  3  2  2  3  2  3  4  2  4  4  4  4  3  1  4  3  4  4  5  2  2  3
  2  2  2  2  3  4  1  2  2  2  2  3  2  2  3  1  2  2  2  3  4  7  5  5
  2  2  1  2  2  2  2  2  3  2  2  5  5  4  3  2  4  2  2  2  3  3  2  4
  2  2 10  3  5  3  4  3  2  2  4  4  4  6  4  6  3  5  4  2  4  4  2  4
  3  2  4  1  2  5  2  2  4  2  2  2  4  3  3  3  2  2  2  5  9  2  6  1
  3  2  1  3  2  3  2  3  2  2  2  3  3  3  2  3  3  1  3  1  1  1  5  6
  2  2  2  3]
[ 2  2  4  4  4  5  2  4  2  4  2  5  2  3  4  4  2  4  4  4  5  3  3  8
  4  3  2  2  5  3  2  3  3  3  4  4  2  4  3  5  3  3  4  2  6  3  5  6
  3  3  3  3  6  2  5  4  3  2  2  7  4  2  2  4  3  4  3  1  3  3  2  3
  4  5  3  2  4  4  3  3  3  4  2  5 

# use 1D, 2D and 3D np-array, and apply indexing and slicing atleast 5 example for each (take example as your wish)

In [226]:
#1D
ar1 = np.array([1,2,3,4,5,6,7])
print(ar1[2])
print(ar1[-1])
print(ar1[1:4])
print(ar1[::2])
print(ar1[::-1])    
print('--------------')


#2D
ar2 = np.array([ [1,2,3,4],[5,6,7,8],[9,10,11,12] ])

print(ar2[1, 2])
print(ar2[0])
print(ar2[:, 1])
print(ar2[0:2, 1:3])
print(ar2[1:2, 1:3])

print('--------------')

#3D
ar3 = np.array([ [[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]  ]) 

print(ar3[2,1,0])
print(ar3[1,1])
print(ar3[0,:,2])
print(ar3[0:2,1,0:2])   
print(ar3[-1,::-1])

3
7
[2 3 4]
[1 3 5 7]
[7 6 5 4 3 2 1]
--------------
7
[1 2 3 4]
[ 2  6 10]
[[2 3]
 [6 7]]
[[6 7]]
--------------
16
[10 11 12]
[3 6]
[[ 4  5]
 [10 11]]
[[16 17 18]
 [13 14 15]]


# stacking and spliting

In [227]:
w = np.array([1, 2, 3])
e = np.array([4, 5, 6])
z = np.concatenate((w,e))
print(z)



[1 2 3 4 5 6]


# use hstack() and vstack()

In [228]:
print(np.vstack((w,e)))
print(np.hstack((w,e)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


# use hsplit() and vsplit()

In [229]:
j = np.array([1, 2, 3,4,5,6])
print(np.split(j,2))

[array([1, 2, 3]), array([4, 5, 6])]
